package main

import (
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
)

// cmdInit generates starter files for a new Beacon installation:
// docker-compose.yml, .mcp.json, and optionally a Rails initializer.
func cmdInit(args []string, stdout, stderr io.Writer) int {
	fs := flag.NewFlagSet("init", flag.ContinueOnError)
	fs.SetOutput(stderr)

	database := fs.String("database", "postgres", "database adapter: postgres, mysql, sqlite")
	ruby := fs.Bool("ruby", false, "generate Rails initializer (config/initializers/beacon.rb)")
	endpoint := fs.String("endpoint", "http://localhost:4680", "Beacon server endpoint URL")

	// Support -d as alias for -database.
	fs.StringVar(database, "d", "postgres", "database adapter (alias for -database)")

	fs.Usage = func() {
		fmt.Fprintf(stderr, "Usage: beacon init [flags]\n\n")
		fmt.Fprintf(stderr, "Generate starter files for a new Beacon installation.\n\n")
		fmt.Fprintf(stderr, "Flags:\n")
		fs.PrintDefaults()
	}

	if err := fs.Parse(args); err != nil {
		return 2
	}

	switch *database {
	case "postgres", "mysql", "sqlite":
	default:
		fmt.Fprintf(stderr, "beacon init: unsupported database %q (choose postgres, mysql, or sqlite)\n", *database)
		return 2
	}

	wrote := 0

	// --- docker-compose.yml ---
	compose := generateCompose(*database)
	n, err := writeFile("docker-compose.yml", compose, stdout, stderr)
	if err != nil {
		fmt.Fprintf(stderr, "beacon init: %v\n", err)
		return 1
	}
	wrote += n

	// --- .mcp.json ---
	mcp := generateMCPJSON(*endpoint)
	n, err = writeFile(".mcp.json", mcp, stdout, stderr)
	if err != nil {
		fmt.Fprintf(stderr, "beacon init: %v\n", err)
		return 1
	}
	wrote += n

	// --- config/initializers/beacon.rb (optional) ---
	if *ruby {
		rb := generateRailsInitializer(*endpoint)
		n, err = writeFile(filepath.Join("config", "initializers", "beacon.rb"), rb, stdout, stderr)
		if err != nil {
			fmt.Fprintf(stderr, "beacon init: %v\n", err)
			return 1
		}
		wrote += n
	}

	// --- Next steps ---
	fmt.Fprintln(stdout)
	if wrote == 0 {
		fmt.Fprintln(stdout, "All files already exist — nothing to write.")
	} else {
		fmt.Fprintln(stdout, "Next steps:")
		if *ruby {
			fmt.Fprintln(stdout, "  docker compose up -d && bundle add beacon-client && rails s")
		} else {
			fmt.Fprintln(stdout, "  docker compose up -d")
		}
		fmt.Fprintf(stdout, "  open %s\n", *endpoint)
		fmt.Fprintln(stdout)
		fmt.Fprintf(stdout, "Wrote %d file(s). Edit them to match your setup.\n", wrote)
	}

	return 0
}

// writeFile writes content to path if the file doesn't already exist.
// Returns 1 if the file was written, 0 if it was skipped.
func writeFile(path, content string, stdout, stderr io.Writer) (int, error) {
	if _, err := os.Stat(path); err == nil {
		fmt.Fprintf(stderr, "  skip %s (already exists)\n", path)
		return 0, nil
	}

	dir := filepath.Dir(path)
	if dir != "." {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return 0, fmt.Errorf("create directory %s: %w", dir, err)
		}
	}

	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return 0, fmt.Errorf("write %s: %w", path, err)
	}

	fmt.Fprintf(stdout, "  wrote %s\n", path)
	return 1, nil
}

func generateCompose(database string) string {
	switch database {
	case "mysql":
		return `# Beacon — docker-compose.yml (MySQL)
# Generated by: beacon init --database mysql
# Edit to match your setup.

services:
  beacon:
    image: ghcr.io/luuuc/beacon:latest
    ports:
      - "127.0.0.1:4680:4680"
    environment:
      BEACON_DATABASE_ADAPTER: "mysql"
      BEACON_DATABASE_URL: "beacon:beacon@tcp(db:3306)/beacon"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: beacon
      MYSQL_USER: beacon
      MYSQL_PASSWORD: beacon
    volumes:
      - beacon_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  beacon_data:
`

	case "sqlite":
		return `# Beacon — docker-compose.yml (SQLite)
# Generated by: beacon init --database sqlite
# Edit to match your setup.

services:
  beacon:
    image: ghcr.io/luuuc/beacon:latest
    ports:
      - "127.0.0.1:4680:4680"
    environment:
      BEACON_DATABASE_ADAPTER: "sqlite3"
      BEACON_DATABASE_PATH: "/data/beacon.db"
    volumes:
      - beacon_data:/data
    restart: unless-stopped

volumes:
  beacon_data:
`

	default: // postgres
		return `# Beacon — docker-compose.yml (PostgreSQL)
# Generated by: beacon init --database postgres
# Edit to match your setup.

services:
  beacon:
    image: ghcr.io/luuuc/beacon:latest
    ports:
      - "127.0.0.1:4680:4680"
    environment:
      BEACON_DATABASE_URL: "postgres://beacon:beacon@db:5432/beacon?sslmode=disable"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: beacon
      POSTGRES_PASSWORD: beacon
      POSTGRES_DB: beacon
    volumes:
      - beacon_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U beacon"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  beacon_data:
`
	}
}

func generateMCPJSON(endpoint string) string {
	return fmt.Sprintf(`{
  "mcpServers": {
    "beacon": {
      "command": "beacon",
      "args": ["mcp", "proxy", "%s/mcp/rpc"],
      "env": { "BEACON_AUTH_TOKEN": "" }
    }
  }
}
`, endpoint)
}

func generateRailsInitializer(endpoint string) string {
	return fmt.Sprintf(`# Beacon observability client
# Generated by: beacon init --ruby
# See: https://github.com/luuuc/beacon

Beacon.configure do |c|
  c.endpoint    = ENV.fetch("BEACON_ENDPOINT", "%s")
  c.auth_token  = ENV["BEACON_AUTH_TOKEN"]
  c.environment = Rails.env
end
`, endpoint)
}
