require "rake/testtask"

Rake::TestTask.new(:test) do |t|
  t.libs    << "lib"
  t.libs    << "spec"
  t.pattern  = "spec/**/*_test.rb"
  t.warning  = false
end

Rake::TestTask.new(:bench) do |t|
  t.libs    << "lib"
  t.libs    << "spec"
  t.pattern  = "spec/bench/*_bench.rb"
  t.warning  = false
end

task default: %i[test bench]
